GET http://localhost:8000/hello
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJndWVzdCI6Imd1ZXN0MSJ9.Nlodi9649pclgmClMN7B8P5e1jkY7nDI-iRYDAs3I8s

###
GET http://localhost:8000/hello
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJndWVzdCI6Imd1ZXN0MiJ9.afMFs2OVPRQ5B9KEOv_BbRPBGHvD47CUpT5ApuwWI1M

###
POST http://localhost:8000/auth
Content-Type: application/json

{
    "passcode": "passcode1"
}

###
GET http://localhost:8000/rsvp
Content-Type: application/json
Party-Token: eyJhbGciOiJIUzI1NiJ9.eyJndWVzdCI6IjNYdVJrZlFITlEwMUhvWWFHV3I1In0.RvU-uYdYFY-PboJPA-wlm17r9a7-GU3vp5to6hEikuo

###
POST http://localhost:8000/rsvp
Content-Type: application/json
Party-Token: eyJhbGciOiJIUzI1NiJ9.eyJndWVzdCI6IjNYdVJrZlFITlEwMUhvWWFHV3I1In0.RvU-uYdYFY-PboJPA-wlm17r9a7-GU3vp5to6hEikuo

{
    "rsvp_status": "Going"
}

###
POST http://localhost:8000/auth
Content-Type: application/json

{
    "passcode": "passcode3"
}
