GET http://localhost:8000/hello
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiZHVtYjEifQ.bsx7iRskkGIXAz0AALDSra8ih_m82J95ex9LCUH9Sww

###
GET http://localhost:8000/rsvp
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiZHVtYjEifQ.bsx7iRskkGIXAz0AALDSra8ih_m82J95ex9LCUH9Sww