-- ============================================================================
-- Passkey Authentication Migration
-- Created: 2025-12-28
-- Description: Adds passkey table for WebAuthn authentication
--
-- This migration enables passwordless authentication using passkeys (WebAuthn).
-- Users can authenticate using biometric (Face ID, Touch ID, Windows Hello)
-- or hardware security keys (YubiKey, etc.).
-- ============================================================================

-- Note: pgcrypto extension should already exist from previous migration
-- If not, uncomment the following line:
-- create extension if not exists "pgcrypto";

-- ============================================================================
-- Passkey Table
-- ============================================================================
-- Stores WebAuthn credentials for passwordless authentication.
-- Each user can have multiple passkeys (different devices).
--
-- Security Model:
-- - Private key: Stored on user's device (Secure Enclave, TPM), never transmitted
-- - Public key: Stored here, used to verify signatures
-- - Challenge-response: Prevents replay attacks
-- - Origin binding: Prevents phishing
--
-- Reference: W3C WebAuthn Level 3 Specification

create table "passkey" (
  -- Primary identifier (UUID v4)
  "id" text not null primary key,

  -- User-provided name for this passkey
  -- Examples: "MacBook Pro", "iPhone 13", "YubiKey 5"
  -- Helps users identify which passkey they're using
  "name" text,

  -- COSE-encoded public key (base64url)
  -- Format: CBOR Object Signing and Encryption (RFC 8152)
  -- For ES256: Contains kty=EC2, alg=-7, crv=P-256, x, y coordinates
  -- For EdDSA: Contains kty=OKP, alg=-8, crv=Ed25519, x coordinate
  "publicKey" text not null,

  -- Foreign key to user table
  -- CASCADE: When user deleted, all their passkeys are deleted
  "userId" text not null references "user" ("id") on delete cascade,

  -- WebAuthn credential ID
  -- Generated by authenticator, used to identify this specific credential
  -- Format: Opaque byte string, typically base64url-encoded
  -- Must be unique across all credentials
  "credentialID" text not null unique,

  -- Signature counter (anti-cloning protection)
  -- Increments with each authentication
  -- If counter doesn't increase: possible cloned authenticator → REJECT
  -- Counter value of 0: Authenticator doesn't support counters (some USB keys)
  "counter" integer not null,

  -- Device type classification
  -- "platform": Built-in authenticator (Touch ID, Face ID, Windows Hello)
  -- "cross-platform": Removable authenticator (USB key, NFC, Bluetooth)
  "deviceType" text not null,

  -- Backup eligibility flag
  -- true: Credential is backed up (iCloud Keychain, Google Password Manager)
  -- false: Credential is device-bound only
  -- Important for recovery: if device lost and backedUp=false, credential lost
  "backedUp" boolean not null,

  -- Supported transports (comma-separated or JSON array)
  -- Values: "usb", "nfc", "ble", "internal", "hybrid"
  -- Example: "internal" for Touch ID, "usb,nfc" for YubiKey
  -- Used by browser to optimize UI (e.g., don't show "insert USB key" for internal)
  "transports" text,

  -- Authenticator Attestation GUID
  -- Identifies the authenticator model (e.g., specific YubiKey version)
  -- Format: 16-byte UUID
  -- Use cases: Security policies ("only allow YubiKeys"), analytics
  "aaguid" text,

  -- Creation timestamp
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- Index on userId for efficient passkey lookup
-- Used when:
-- - Listing user's passkeys in settings UI
-- - Finding credentials during authentication (resident key flow)
-- - Deleting user (cascade delete performance)
create index "passkey_userId_idx" on "passkey" ("userId");

-- Index on credentialID for efficient authentication
-- Used when:
-- - Browser provides credentialID during authentication assertion
-- - Server needs to lookup stored public key for signature verification
-- Query pattern: WHERE credentialID = ?
-- Most frequent query (every authentication), must be fast
create index "passkey_credentialID_idx" on "passkey" ("credentialID");

-- ============================================================================
-- Table Comments (PostgreSQL Documentation)
-- ============================================================================

comment on table "passkey" is
  'WebAuthn passkey credentials for passwordless authentication. ' ||
  'Stores public keys; private keys never leave user devices.';

comment on column "passkey"."publicKey" is
  'COSE-format public key (base64url). Used to verify authentication signatures.';

comment on column "passkey"."credentialID" is
  'Unique credential identifier. Generated by authenticator, used by browser during authentication.';

comment on column "passkey"."counter" is
  'Signature counter for replay attack prevention. Must strictly increase or equal zero (if unsupported).';

comment on column "passkey"."deviceType" is
  'Authenticator type: "platform" (built-in) or "cross-platform" (removable USB key).';

comment on column "passkey"."backedUp" is
  'Whether credential is backed up to cloud (iCloud, Google). Important for device loss recovery.';

comment on column "passkey"."transports" is
  'Supported communication methods: usb, nfc, ble, internal, hybrid. Browser uses this to optimize UX.';

comment on column "passkey"."aaguid" is
  'Authenticator Attestation GUID. Identifies specific authenticator model. Used for security policies.';

-- ============================================================================
-- Verification Table (Magic Links)
-- ============================================================================

-- Note: The "verification" table should already exist from Better Auth.
-- It stores magic link tokens for passwordless registration and recovery.
-- Structure:
--   - id: Primary key
--   - identifier: Email address
--   - value: Hashed token (SHA-256)
--   - expiresAt: Token expiration (typically 5 minutes)
--   - createdAt, updatedAt: Timestamps
--
-- No changes needed to this table for passkey implementation.

-- ============================================================================
-- Existing Tables (No Modifications Required)
-- ============================================================================

-- user table: No changes needed
--   - email field used for magic link delivery
--   - No password requirement (handled by Better Auth)
--
-- session table: No changes needed
--   - Standard session management continues to work
--
-- account table: No changes needed
--   - Password hashes will be null/unused after migration
--   - Table structure unchanged for compatibility

-- ============================================================================
-- Data Migration Notes
-- ============================================================================

-- This is an ADDITIVE migration:
-- ✓ Creates new passkey table
-- ✓ Does not modify existing tables
-- ✓ Does not delete or migrate existing data
-- ✓ Existing password-based sessions continue to work during transition
--
-- Migration Path:
-- 1. Deploy this migration
-- 2. Deploy application code with passkey support
-- 3. Existing users can continue using passwords temporarily
-- 4. Prompt users to set up passkeys
-- 5. After transition period, disable password authentication
--
-- Rollback Strategy:
-- To rollback: DROP TABLE passkey;
-- Safe because no foreign keys reference this table.

-- ============================================================================
-- Security Considerations
-- ============================================================================

-- 1. Public Key Exposure: Safe
--    - Public keys are public by definition
--    - Cannot be used to authenticate without private key
--    - Database breach does NOT compromise authentication
--
-- 2. Signature Counter Critical
--    - Application MUST verify counter strictly increases
--    - Failure indicates cloned authenticator
--    - Action: Revoke credential, alert user
--
-- 3. Challenge Freshness
--    - Server must generate cryptographically random challenges
--    - One-time use only (store used challenges temporarily)
--    - Expire challenges after 5 minutes
--
-- 4. Origin Validation
--    - Always verify clientData.origin matches expected domain
--    - Prevents MITM and phishing attacks
--
-- 5. HTTPS Required
--    - WebAuthn only works in secure contexts
--    - Production: HTTPS mandatory
--    - Development: localhost allowed

-- ============================================================================
-- Query Patterns and Performance
-- ============================================================================

-- Authentication (most frequent):
-- SELECT publicKey, counter, userId
-- FROM passkey
-- WHERE credentialID = $1;
-- Performance: O(1) via index, < 1ms
--
-- List user's passkeys (settings page):
-- SELECT id, name, deviceType, backedUp, createdAt
-- FROM passkey
-- WHERE userId = $1
-- ORDER BY createdAt DESC;
-- Performance: O(k) where k = number of user's passkeys, typically < 5
--
-- Delete passkey:
-- DELETE FROM passkey WHERE id = $1 AND userId = $2;
-- Performance: O(1), verifies ownership via userId check

-- ============================================================================
-- End of Migration
-- ============================================================================
