name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-bouncer:
    runs-on: "ubuntu-latest"
    env:
      working-directory: app/bouncer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.0.0
          cache: npm
          cache-dependency-path: app/bouncer/package-lock.json

      - name: Install
        working-directory: ${{env.working-directory}}
        run: npm ci

      - name: Test
        working-directory: ${{env.working-directory}}
        run: npm test

  build-pregame:
    runs-on: "ubuntu-latest"
    env:
      working-directory: app/pregame
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        working-directory: ${{env.working-directory}}
        run: cargo build
